export default [
    '888sport',
    'AdmiralYES',
    'Bbet',
    'Bet365',
    'Betclic',
    'Betfair',
    'Betflag',
    'Betland',
    'Better',
    'Betway',
    'Bwin',
    'Codere',
    'DomusBet',
    'Enjoybet',
    'Eplay24',
    'Eurobet',
    'FantasyTeam',
    'Gioco Digitale',
    'Goldbet',
    'LeoVegas',
    'Marathonbet',
    'Merkur Win',
    'NetBet',
    'Newgioco',
    'Pinterbet',
    'Planetwin365',
    'Replatz',
    'SISAL',
    'Sky Bet',
    'SNAI',
    'Sportitaliabet',
    'SportPesa',
    'StarCasinò',
    'Stanleybet',
    'StarVegas',
    'Unibet',
    'William Hill'
];