export default [
    {icon: '', value: '888sport', label: '888sport',},
    {icon: '', value: 'AdmiralYES', label: 'AdmiralYES',},
    {icon: '', value: 'Bbet', label: 'Bbet',},
    {icon: '', value: 'Bet365', label: 'Bet365',},
    {icon: '', value: 'Betclic', label: 'Betclic',},
    {icon: '', value: 'Betfair', label: 'Betfair',},
    {icon: '', value: 'Betflag', label: 'Betflag',},
    {icon: '', value: 'Betland', label: 'Betland',},
    {icon: '', value: 'Better', label: 'Better',},
    {icon: '', value: 'Betway', label: 'Betway',},
    {icon: '', value: 'Bwin', label: 'Bwin',},
    {icon: '', value: 'Codere', label: 'Codere',},
    {icon: '', value: 'DomusBet', label: 'DomusBet',},
    {icon: '', value: 'Enjoybet', label: 'Enjoybet',},
    {icon: '', value: 'Eplay24', label: 'Eplay24',},
    {icon: '', value: 'Eurobet', label: 'Eurobet',},
    {icon: '', value: 'FantasyTeam', label: 'FantasyTeam',},
    {icon: '', value: 'Gioco Digitale', label: 'Gioco Digitale',},
    {icon: '', value: 'Goldbet', label: 'Goldbet',},
    {icon: '', value: 'LeoVegas', label: 'LeoVegas',},
    {icon: '', value: 'Marathonbet', label: 'Marathonbet',},
    {icon: '', value: 'Merkur Win', label: 'Merkur Win',},
    {icon: '', value: 'NetBet', label: 'NetBet',},
    {icon: '', value: 'Newgioco', label: 'Newgioco',},
    {icon: '', value: 'Pinterbet', label: 'Pinterbet',},
    {icon: '', value: 'Planetwin365', label: 'Planetwin365',},
    {icon: '', value: 'Replatz', label: 'Replatz',},
    {icon: '', value: 'SISAL', label: 'SISAL',},
    {icon: '', value: 'Sky Bet', label: 'Sky Bet',},
    {icon: '', value: 'SNAI', label: 'SNAI',},
    {icon: '', value: 'Sportitaliabet', label: 'Sportitaliabet',},
    {icon: '', value: 'SportPesa', label: 'SportPesa',},
    {icon: '', value: 'StarCasinò', label: 'StarCasinò',},
    {icon: '', value: 'Stanleybet', label: 'Stanleybet',},
    {icon: '', value: 'StarVegas', label: 'StarVegas',},
    {icon: '', value: 'Unibet', label: 'Unibet',},
    {icon: '', value: 'William Hill', label: 'William Hill',},
];