import React from "react";
import CreateNewServiceButton from "./App/components/CreateNewServiceButton";
import CreateTipButton from "./App/components/CreateTipButton";

export default {
  items: [
    {
      id: "menu utente",
      title: "Menu utente",
      type: "group",
      icon: "icon-navigation",
      children: [
        {
          id: "dashboard",
          title: "Dashboard",
          type: "item",
          icon: "feather icon-home",
          url: "/dashboard/default",
          classes: "ni",
          role: 4,
        },
        {
          id: "pending-tips",
          title: "Tips",
          type: "item",
          icon: "feather icon-inbox",
          url: "/dashboard/pending-tips",
          classes: "ni",
          role: 4,
        },
        {
          id: "balance",
          title: "Bilancio",
          type: "item",
          icon: "feather icon-trending-up",
          url: "/dashboard/balance",
          classes: "ni",
          role: 4,
        },
        {
          id: "active-services",
          title: "Iscrizioni",
          type: "item",
          icon: "feather icon-box",
          url: "/dashboard/my-services",
          classes: "ni",
          role: 4,
        },
        {
          id: "details",
          title: "Detaglio Servizio",
          type: "item",
          icon: "feather icon-user",
          url: "/dashboard/details",
          classes: "ni",
          role: 0,
          hidden: true
        },
        {
          id: "details",
          title: "Detaglio Tip",
          type: "item",
          icon: "feather icon-user",
          url: "/tip/detail",
          classes: "ni",
          role: 0,
          hidden: true
        },
        {
          id: "payments",
          title: "Storico Pagamenti",
          type: "item",
          icon: "fa fa-history",
          url: "/profile/payments",
          classes: "ni",
          role: 0,
        },
        {
          id: "profile",
          title: "Profilo",
          type: "item",
          icon: "feather icon-user",
          url: "/profile",
          classes: "ni",
          role: 0,
        },
        {
          id: "settings",
          title: "Impostazioni",
          type: "item",
          icon: "feather icon-settings",
          classes: "ni",
          role: 3,
          url: "/settings",
        },
        {
          id: "admin",
          title: "Amministratore",
          type: "collapse",
          icon: "feather icon-settings",
          classes: "ni",
          hidden: true,
          role: 5,
          children: [
            {
              id: "Users",
              title: "Utenti",
              type: "item",
              icon: "feather icon-users",
              classes: "ni",
              url: "/users",
              role: 6,
              hidden: true,
            },
          ],
        },
        {
          id: "account",
          title: "Impostazioni profilo",
          type: "item",
          icon: "feather icon-user",
          classes: "ni",
          url: "/settings",
          role: 0,
          hidden: true,
        },
      ],
    },
    {
      id: "menu-generica",
      title: "Sfoglia",
      type: "group",
      icon: "icon-navigation",
      children: [
        {
          id: "marketplace",
          title: "Servizi",
          type: "item",
          icon: "feather icon-shopping-cart",
          classes: "ni",
          url: "/dashboard/marketplace",
          role: 3
        },
        {
          id: "tipsters",
          title: "Tipsters",
          type: "item",
          icon: "feather icon-users",
          role: 0,
          url: "/all-tipsters",
          classes: "ni",
        },
        {
          id: "bookmakerstable",
          title: "Bookmakers",
          type: "item",
          icon: "feather icon-book",
          classes: "ni",
          role: 0,
          url: "/bookmakersTable",
        },
      ]
    },
    {
      id: "menu tipster",
      title: "Menu tipster",
      type: "group",
      classes: "ni",
      icon: "icon-navigation",
      role: 5,
      children: [
        {
          id: "my-services",
          title: "I miei servizi",
          classes: "ni",
          type: "item",
          icon: "feather icon-package",
          url: "/dashboard/tipster/services",
          role: 5,
          rightButton: <CreateNewServiceButton />,
        },
        {
          id: "my-tips",
          title: "Le mie Tips",
          classes: "ni",
          type: "item",
          icon: "fa fa-rss",
          url: "/dashboard/tipster/pools",
          role: 5,
          rightButton: <CreateTipButton />,
        },
        {
          id: "create-service",
          title: "Pubblica un servizio",
          type: "item",
          classes: "ni",
          icon: "feather icon-book",
          url: "/dashboard/tipster/createService",
          role: 5,
          hidden: true
        },
        {
          id: "new-tips",
          title: "Crea tip",
          type: "item",
          icon: "feather icon-bookmark",
          classes: "ni",
          url: "/dashboard/tipster/createTip",
          hidden: true,
          role: 5,
        },
        {
          id: "wallet",
          title: "Wallet",
          type: "item",
          icon: "feather icon-credit-card",
          classes: "ni",
          url: "/wallet",
          role: 5,
        }
      ]
    }
  ],
};
